---
modbustcp_remote_server:
  ip: "10.72.1.88"
  port: 502

opcua_server:
  ip: "10.72.1.24"
  port: "4841"

# This configuration is for AGV door kits sim environment
# project number: 

polling_cycle_seconds: 1

nodes:
- object_node:
    name: "WagoGA3DoorKitSim"
    nodes:
    - variable_node:
        modbus_address: 12288
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_kit_rec_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12288
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_kit_rec_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12289
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_kit_rec_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12289
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_kit_rec_request
        type: boolean
    - variable_node:
        modbus_address: 12292
        modbus_type: holding_register
        name: lh_kit_rec_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12293
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_kit_rec_count
        type: byte
    - variable_node:
        modbus_address: 12294
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_kit_del_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12294
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_kit_del_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12295
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_kit_del_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12295
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_kit_del_request
        type: boolean
    - variable_node:
        modbus_address: 12298
        modbus_type: holding_register
        name: lh_kit_del_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12299
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_kit_del_count
        type: byte
    - variable_node:
        modbus_address: 12300
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_rec1_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12300
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_assy_rec1_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12301
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_rec1_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12301
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_assy_rec1_request
        type: boolean
    - variable_node:
        modbus_address: 12304
        modbus_type: holding_register
        name: lh_assy_rec1_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12305
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_rec1_count
        type: byte
    - variable_node:
        modbus_address: 12306
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_rec2_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12306
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_assy_rec2_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12307
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_rec2_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12307
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_assy_rec2_request
        type: boolean
    - variable_node:
        modbus_address: 12310
        modbus_type: holding_register
        name: lh_assy_rec2_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12311
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_rec2_count
        type: byte
    - variable_node:
        modbus_address: 12312
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_del_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12312
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_assy_del_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12313
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_del_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12313
        modbus_bit: 8
        modbus_type: holding_register
        name: lh_assy_del_request
        type: boolean
    - variable_node:
        modbus_address: 12316
        modbus_type: holding_register
        name: lh_assy_del_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12317
        modbus_bit: 0
        modbus_type: holding_register
        name: lh_assy_del_count
        type: byte
    - variable_node:
        modbus_address: 12318
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_kit_rec_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12318
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_kit_rec_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12319
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_kit_rec_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12319
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_kit_rec_request
        type: boolean
    - variable_node:
        modbus_address: 12322
        modbus_type: holding_register
        name: rh_kit_rec_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12323
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_kit_rec_count
        type: byte
    - variable_node:
        modbus_address: 12324
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_kit_del_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12324
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_kit_del_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12325
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_kit_del_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12325
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_kit_del_request
        type: boolean
    - variable_node:
        modbus_address: 12328
        modbus_type: holding_register
        name: rh_kit_del_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12329
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_kit_del_count
        type: byte
    - variable_node:
        modbus_address: 12330
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_rec1_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12330
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_assy_rec1_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12331
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_rec1_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12331
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_assy_rec1_request
        type: boolean
    - variable_node:
        modbus_address: 12334
        modbus_type: holding_register
        name: rh_assy_rec1_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12335
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_rec1_count
        type: byte
    - variable_node:
        modbus_address: 12336
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_rec2_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12336
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_assy_rec2_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12337
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_rec2_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12337
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_assy_rec2_request
        type: boolean
    - variable_node:
        modbus_address: 12340
        modbus_type: holding_register
        name: rh_assy_rec2_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12341
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_rec2_count
        type: byte
    - variable_node:
        modbus_address: 12342
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_del_ok_to_leave
        type: boolean
    - variable_node:
        modbus_address: 12342
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_assy_del_agv_leaving
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12343
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_del_sim_station_down
        opc_writable: true
        type: boolean
    - variable_node:
        modbus_address: 12343
        modbus_bit: 8
        modbus_type: holding_register
        name: rh_assy_del_request
        type: boolean
    - variable_node:
        modbus_address: 12346
        modbus_type: holding_register
        name: rh_assy_del_agv_number
        opc_writable: true
        type: word
    - variable_node:
        modbus_address: 12347
        modbus_bit: 0
        modbus_type: holding_register
        name: rh_assy_del_count
        type: byte