---
modbustcp_remote_server:
  ip: "10.72.1.88"
  port: 502

opcua_server:
  ip: "127.0.0.1"
  port: "4841"

polling_cycle_seconds: 0.3

nodes:
  - object_node:
      name: "WagoGA3SeatSim"
      nodes:
        - variable_node:
            name: "word0"
            type: "int"
            modbus_type: "holding_register"
            modbus_address: 12288

        #mn1 drvr
        # full
        - variable_node:
            name: "mn1_drvr_full_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12388
            modbus_bit: 0
        - variable_node:
            name: "mn1_drvr_full_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12389
            opc_writable: True
        - variable_node:
            name: "mn1_drvr_full_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12390
            modbus_bit: 0
        - variable_node:
            name: "mn1_drvr_full_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12390
            modbus_bit: 8
            opc_writable: True
        # empty
        - variable_node:
            name: "mn1_drvr_empty_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12398
            modbus_bit: 0
        - variable_node:
            name: "mn1_drvr_empty_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12399
            opc_writable: True
        - variable_node:
            name: "mn1_drvr_empty_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12400
            modbus_bit: 0
        - variable_node:
            name: "mn1_drvr_empty_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12400
            modbus_bit: 8
            opc_writable: True

        #mn1 psgr
        # full
        - variable_node:
            name: "mn1_psgr_full_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12408
            modbus_bit: 0
        - variable_node:
            name: "mn1_psgr_full_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12409
            opc_writable: True
        - variable_node:
            name: "mn1_psgr_full_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12410
            modbus_bit: 0
        - variable_node:
            name: "mn1_psgr_full_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12410
            modbus_bit: 8
            opc_writable: True
        # empty
        - variable_node:
            name: "mn1_psgr_empty_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12418
            modbus_bit: 0
        - variable_node:
            name: "mn1_psgr_empty_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12419
            opc_writable: True
        - variable_node:
            name: "mn1_psgr_empty_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12420
            modbus_bit: 0
        - variable_node:
            name: "mn1_psgr_empty_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12420
            modbus_bit: 8
            opc_writable: True

        #mn1 rear
        # full
        - variable_node:
            name: "mn1_rear_full_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12428
            modbus_bit: 0
        - variable_node:
            name: "mn1_rear_full_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12429
            opc_writable: True
        - variable_node:
            name: "mn1_rear_full_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12430
            modbus_bit: 0
        - variable_node:
            name: "mn1_rear_full_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12430
            modbus_bit: 8
            opc_writable: True
        # empty
        - variable_node:
            name: "mn1_rear_empty_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12438
            modbus_bit: 0
        - variable_node:
            name: "mn1_rear_empty_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12439
            opc_writable: True
        - variable_node:
            name: "mn1_rear_empty_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12440
            modbus_bit: 0
        - variable_node:
            name: "mn1_rear_empty_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12440
            modbus_bit: 8
            opc_writable: True

        #mn2 drvr
        # full
        - variable_node:
            name: "mn2_drvr_full_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12488
            modbus_bit: 0
        - variable_node:
            name: "mn2_drvr_full_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12489
            opc_writable: True
        - variable_node:
            name: "mn2_drvr_full_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12490
            modbus_bit: 0
        - variable_node:
            name: "mn2_drvr_full_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12490
            modbus_bit: 8
            opc_writable: True
        # empty
        - variable_node:
            name: "mn2_drvr_empty_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12498
            modbus_bit: 0
        - variable_node:
            name: "mn2_drvr_empty_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12499
            opc_writable: True
        - variable_node:
            name: "mn2_drvr_empty_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12500
            modbus_bit: 0
        - variable_node:
            name: "mn2_drvr_empty_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12500
            modbus_bit: 8
            opc_writable: True

        #mn2 psgr
        # full
        - variable_node:
            name: "mn2_psgr_full_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12508
            modbus_bit: 0
        - variable_node:
            name: "mn2_psgr_full_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12509
            opc_writable: True
        - variable_node:
            name: "mn2_psgr_full_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12510
            modbus_bit: 0
        - variable_node:
            name: "mn2_psgr_full_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12510
            modbus_bit: 8
            opc_writable: True
        # empty
        - variable_node:
            name: "mn2_psgr_empty_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12518
            modbus_bit: 0
        - variable_node:
            name: "mn2_psgr_empty_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12519
            opc_writable: True
        - variable_node:
            name: "mn2_psgr_empty_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12520
            modbus_bit: 0
        - variable_node:
            name: "mn2_psgr_empty_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12520
            modbus_bit: 8
            opc_writable: True

        #mn2 rear
        # full
        - variable_node:
            name: "mn2_rear_full_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12528
            modbus_bit: 0
        - variable_node:
            name: "mn2_rear_full_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12529
            opc_writable: True
        - variable_node:
            name: "mn2_rear_full_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12530
            modbus_bit: 0
        - variable_node:
            name: "mn2_rear_full_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12530
            modbus_bit: 8
            opc_writable: True
        # empty
        - variable_node:
            name: "mn2_rear_empty_cnv_pp_empty"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12538
            modbus_bit: 0
        - variable_node:
            name: "mn2_rear_empty_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12539
            opc_writable: True
        - variable_node:
            name: "mn2_rear_empty_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12540
            modbus_bit: 0
        - variable_node:
            name: "mn2_rear_empty_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12540
            modbus_bit: 8
            opc_writable: True

        # mty_in01
        - variable_node:
            name: "mty_in01_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12589
            opc_writable: True
        - variable_node:
            name: "mty_in01_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12590
            modbus_bit: 0
        - variable_node:
            name: "mty_in01_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12590
            modbus_bit: 8
            opc_writable: True
        # mn1_sout
        - variable_node:
            name: "mn1_sout_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12599
            opc_writable: True
        - variable_node:
            name: "mn1_sout_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12600
            modbus_bit: 0
        - variable_node:
            name: "mn1_sout_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12600
            modbus_bit: 8
            opc_writable: True
        # mty_in02
        - variable_node:
            name: "mty_in02_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12609
            opc_writable: True
        - variable_node:
            name: "mty_in02_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12610
            modbus_bit: 0
        - variable_node:
            name: "mty_in02_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12610
            modbus_bit: 8
            opc_writable: True
        # mn2_sout
        - variable_node:
            name: "mn2_sout_agv_number"
            type: "word"
            modbus_type: "holding_register"
            modbus_address: 12619
            opc_writable: True
        - variable_node:
            name: "mn2_sout_cnv_ok_to_leave"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12620
            modbus_bit: 0
        - variable_node:
            name: "mn2_sout_agv_leaving"
            type: "boolean"
            modbus_type: "holding_register"
            modbus_address: 12620
            modbus_bit: 8
            opc_writable: True
